# Generated by Django 4.2 on 2023-05-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_billing_slug_alter_blog_slug_alter_cart_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dept_name']},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='media/categories'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(null=True, upload_to='media/department'),
        ),
    ]
