# Generated by Django 4.2 on 2023-05-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_blog_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='labels',
            field=models.CharField(choices=[('hot', 'Hot'), ('new', 'New'), ('sale', 'Sale'), ('default', 'Default')], default='new', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('in_stock', 'In Stock'), ('out_stock', 'Out of stock')], default='in_stock', max_length=100),
        ),
    ]
