# Generated by Django 4.2 on 2023-05-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_billing_slug_alter_blog_slug_alter_cart_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='information',
            field=models.TextField(blank=True),
        ),
    ]
