# Generated by Django 4.2 on 2023-05-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_wishlist_created_at_wishlist_modified_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='price',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
