# Generated by Django 4.2 on 2023-05-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_billing_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
