# Generated by Django 4.2 on 2023-05-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_khaltitransactionrecord_order_orderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_payment',
        ),
    ]
