# Generated by Django 4.2 on 2023-05-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_remove_order_total_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khaltitransactionrecord',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='items',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='KhaltiTransactionRecord',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
